apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
    labels:
        app: expense-tracker
        tier: db
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: local-storage