apiVersion: v1
kind: Service
metadata:
    name: expense-app
    labels:
        app: expense-tracker
        tier: app
spec:
    ports:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30808
    selector:
        app: expense-tracker
        tier: app