apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
        app: expense-tracker
        tier: db
spec:
    ports:
    type: NodePort
    ports:
    - port: 30017
      targetPort: 27017
      nodePort: 30017
    selector:
        app: expense-tracker
        tier: db